### PR TITLE
Update armor.json

### PR DESCRIPTION
**Pull request by Stretop**
Covers for armors updated to format for current experimental version of DDA

### CODE REVIEW

**Comment by pawnishoovy** [comment]
has the new inventory system been debugged yet? ive been refraining from updating so it remained compatible with 10614 (or whatever the last build was)

**Comment by Stretop** [comment]
Hard to say for sure. I have not met any bugs so far, but I have not tested that system specifically. Seems to work fine to me, except that "survivor toolbelt" problem.

> ive been refraining from updating so it remained compatible with 10614

Wouldn't it be easier to create a release for that version and then keep master branch compatible with current experimental?

**Comment by Sons-of-Man** [comment]
I have met one bug so far on Build 10914 with heavy survivor leather robes, throws a invalid body part id when it is selected in crafting menu and forces me out of the menu unable to craft it. Same with extra-light survivor hood and probably more, have not explored the rest of the mod yet.

**Comment by pawnishoovy** [comment]
yea you're right about the release thing. merging and moving on now, next up is adding longest sides i suppose

**Pull request merged**
